### ISSUE TITLE
What is the project about?

### ISSUE THREAD

**Issue by Beliavsky** [Hori-Lab/SIS#3]
Could you describe what the project is about in the Readme? Is there an associated publication? I would like to add it to my list https://github.com/Beliavsky/Fortran-code-on-GitHub/blob/main/README.md .

**Comment by naotohori** [comment]
Hello, thank you for finding this project. This code is for molecular dynamics simulations using a coarse-grained RNA model (SIS = Single-Interaction-Site model) that we are still developing. It's not published yet. Molecular Dynamics would be the right category.
